= Potato Cheese Soup
:keywords: 
:navtitle: 
:description:
:experimental: 
:hardbreaks-option:
:imagesdir: ../images
:source-highlighter: highlight.js
:icons: font
:table-stripes: even
:tabs:
:tabs-sync-option:

== Ingredients

- [ ] 2 tablespoons butter
- [ ] 1/2 cup chopped onion
- [ ] 6 cups peeled and cubed potatoes
- [ ] 2 14 oz. cans chicken broth
- [ ] 1 teaspoon salt
- [ ] 1/2 teaspoon black pepper
- [ ] 1/8 tsp red pepper flakes
- [ ] 2 tablespoons dried parsley
- [ ] 2 tablespoons cornstarch
- [ ] 2 tablespoons water
- [ ] 3 oz. cream cheese, cut into cubes
- [ ] 1 cup shredded cheddar cheese
- [ ] 2 cups half and half (can use fat free but soup will be thinner)
- [ ] 6 slices crisp-cooked bacon, crumbled
- [ ] 1 cup frozen corn (we don't add these)

== Instructions
Select Saute and add butter to the pressure cooker pot. When butter is melted, add the onion and cook, stirring ocvcasionally until the onion is tender, about 5 minutes. Add 1 can chicken broth, salt, pepper, red pepper flakes, and parsley to the onions.

Put the steamer basket in the pressure cooker pot. Add the diced potatoes. Lock lid in place, select "High Pressure" and "4 minutes" cook time and start. When timer beeps, turn off pressure cooker, wait 5 minutes, then do a quick pressure release. Carefully remove potatoes and steamer basket from the pressure cooking pot.

In a small bowl, dissolve cornstarch in 2 tablespoons water. Select simmer and add cornstarch mixture to the pot stirring constantly. Add cubed cream cheese and shredded cheese. Stir until cheese is melted. Add remaining can of chicken broth, half and half, corn, crumbled bacon, and cooked potatoes, and heat through but do not bring to a boil.