= Pork Shoulder
:keywords: 
:navtitle: 
:description:
:experimental: 
:hardbreaks-option:
:imagesdir: ../images
:source-highlighter: highlight.js
:icons: font
:table-stripes: even
:tabs:
:tabs-sync-option:

Ingredients
1 (8 pound) pork shoulder roast 1 quart apple cider, or as needed BBQ Rub: 
5 tablespoons white sugar
5 tablespoons light brown sugar 
2 tablespoons kosher salt 
2 tablespoons paprika 
1 tablespoon onion powder 
1 tablespoon freshly ground black pepper 
1 tablespoon garlic powder 
1 onion, chopped
White Onion, Large 
 3 cups hickory chips, or more as needed, soaked in water

Recipe 
Prep 10 m
Cook 8 h
Ready In 20 h 10 m
Place pork shoulder in a large pot and add enough apple cider to cover. Combine white sugar, brown sugar, salt, paprika, onion powder, black pepper, and garlic powder in a bowl. Mix about 1/4 cup sugar rub into cider; reserve remaining rub.
Cover pot and refrigerate for 12 hours.
Prepare smoker to about 210 degrees F (99 degrees C). Add enough wood chips to smoker.
Pour cider brine into the water pan of the smoker; add onion and about 1/4 cup more sugar rub. Spread remaining rub over pork shoulder. Transfer pork to the center of smoker.
Smoke pork until very tender, about 8 hours. Monitor hickory chips and liquid, adding more wood and water, respectively, as needed. Transfer pork to a large platter and cool for 30 minutes before shredding with forks.


Alternative
Mix dry ingredients in 1 quart apple cider mix thoroughly. Inject pork with mixture, place cut white onions on top of pork and let marinade for 12 hours
