= Beef Stew
:keywords: 
:navtitle: 
:description:
:experimental: 
:hardbreaks-option:
:imagesdir: ../images
:source-highlighter: highlight.js
:icons: font
:table-stripes: even
:tabs:
:tabs-sync-option:

== Ingrediants
2 pounds stewing beef trimmed and cubed
3 tablespoons all-purpose flour
½ teaspoon garlic powder
½ teaspoon salt
½ teaspoon black pepper
3 tablespoons olive oil
1 onion chopped
6 cups beef broth
½ cup red wine optional
1 pound potatoes peeled and cubed
4 carrots cut into 1 inch pieces
4 ribs celery cut into 1 inch pieces
3 tablespoons tomato paste
+++ <s>1 teaspoon dried rosemary or 1 sprig fresh</s> +++
2 tablespoons cornstarch or as needed
2 tablespoons water or as needed

== Directions
. Combine flour, garlic powder and salt & pepper. Toss beef in flour mixture. 
. Heat olive oil in a large Dutch oven or pot. Cook the beef and onions until browned.
. Add beef broth and red wine while scraping up any brown bits in the pan.
. Stir in all remaining ingredients except for peas, cornstarch and water. Reduce heat to medium low, cover and simmer 1 hour or until beef is tender (up to 90 minutes).
. Mix equal parts cornstarch and water to create a slurry. Slowly add the slurry to the boiling stew to reach desired consistency (you may not need all of the slurry, if you'd like a thicker stew, you can add extra).  
. Simmer 5-10 minutes before serving . Season with salt & pepper to taste.