= Jambalaya
:keywords: 
:navtitle: 
:description:
:experimental: 
:hardbreaks-option:
:imagesdir: ../images
:source-highlighter: highlight.js
:icons: font
:table-stripes: even
:tabs:
:tabs-sync-option:

== Ingredients
Chicken thighs
andouille sausage
Bell pepper
yellow onion
celery
2-4oz tomato paste
garlic paste (can sub with minced garlic)
2 cups white rice
4 cups chicken broth

=== Seasoning
Garlic Powder
Onion Powder
Smoked Paprika
Cayenne Pepper (careful this is spicy)


== Prep
Dice the "Holy Trinity" (Bell Pepper/Onion/Celery) and mix together in a bowl.
Slice the sausage, and cut down the chicken thighs. (Bigger is better)
In a mixing bowl put the chopped/cut chicken thighs, add/drizzle olive oil over the chicken and evenly cover with spices/seasoning.

== Directions
Get your pan hot, add olive oil to pan. 
Brown the sausage, once done remove but leave the oil!!!
Add chicken thighs to pan, cook until done.
Remove and leave the oil again.

saute the trinity, this will soak up the existing oil and flavor from the sausage and chicken.
Once the onions are translucent, add in the tomato paste and garlic
after about 30 seconds add dry rice and roast for about a min or so.
add chicken broth, sausage, chicken, bring to boil.
reduce heat to simmer, cover for 20 minutes to cook the rice.
