= Dragon's Breath Chili
:keywords: 
:navtitle: 
:description:
:experimental: 
:hardbreaks-option:
:imagesdir: ../images
:source-highlighter: highlight.js
:icons: font
:table-stripes: even
:tabs:
:tabs-sync-option:

== Ingredients
3 tablespoons bacon grease or canola oil
2 tablespoons unsalted butter
3 Anaheim chiles, roasted, peeled, chopped
3 poblano chiles, roasted, peeled, chopped
2 red bell peppers, diced
2 jalapenos chiles, minced
2 yellow onions, diced
1 head garlic, minced
1 pound boneless chuck, trimmed and cut into 1/4-inch cubes
2 pounds ground beef, coarse grind
1 pound bulk Italian sausage
3 tablespoons chili powder
2 teaspoons cayenne pepper
2 teaspoons ground coriander
2 teaspoons ground cumin
2 teaspoons granulated garlic
2 teaspoons granulated onion
2 teaspoons hot paprika
2 teaspoons kosher salt
2 teaspoons freshly ground black pepper
2 cups tomato sauce
1 cup tomato paste
12 ounces lager beer
1 cup chicken stock
Two 15.5-ounce cans kidney beans, with juice
Two 15.5-ounce cans pinto beans, with juice
Double-Fried French Fries, for serving, recipe follows
Saltine crackers, for garnish
1 bunch green onions, thinly sliced
1 cup shredded Cheddar

== Directions
. Add the bacon grease and butter to a large stockpot over high heat. Add the Anaheim chiles, poblano chiles, red bell peppers, jalapeno chiles and onions, and cook until caramelized, about 5 minutes. Add the garlic and saute 1 minute longer. Add the chuck and brown, about 4 minutes. Add the ground beef and sausage and brown, stirring gently, trying not to break up the ground beef too much. Cook until the meat is nicely browned and cooked through, 7 to 10 minutes. Add the chili powder, cayenne, coriander, cumin, granulated garlic, granulated onion, paprika, salt and black pepper, and cook until fragrant, about 1 minute.

. Add the tomato sauce and paste, and stir to caramelize, about 2 minutes. Stir in the beer and stock. Add the kidney and pinto beans; lower the heat and simmer, about 2 hours.

. Serve the chili in bowls over Double-Fried French Fries and garnish with crackers, green onions and Cheddar.