= Sweet and Sour Mustard Barbeque Sauce
:keywords: 
:navtitle: 
:description:
:experimental: 
:hardbreaks-option:
:imagesdir: ../images
:source-highlighter: highlight.js
:icons: font
:table-stripes: even
:tabs:
:tabs-sync-option:

Sweet and Sour Mustard Barbeque Sauce
This tasty sauce recipe is made by combining:
	• 1/2 cup of prepared yellow mustard
	• 1/4 cup of cider vinegar
	• 3 tablespoons of brown sugar (dark)
	• 1/2 teaspoon of paprika
	• 1/2 teaspoon of Worscestershire sauce
	• 1/2 teaspoon white pepper
	• 1/2 teaspoon of cayenne pepper (powdered)
	• 1/4 teaspoon of black pepper
To mix the ingredients, I find it easiest to add everything to a small, tightly sealing jar, and shake the livin' daylights out of it! Not only do you get a great sauce with this recipe, but you also get a nice little workout!
This mustard-based barbecue sauce has a smooth consistency...the tartness of the vinegar is balanced by the brown sugar sweetness. This is my favorite of all the non-tomato based bbq sauces.
Occasionally I put this sauce together with more cayenne pepper. One full teaspoon of the red powder gives this sauce an enjoyable level of heat! 
The flavor of this mustard-based sauce works very well with pork and chicken. Actually, I keep a squeeze bottle of it around for other stuff, like fish and meatloaf. I've even been known to dip my french fries in this one!
This barbecue sauce is good to baste with, but like other sauces with sugar, to prevent burning, it should only be used on the meat as it's finishing up on the smoker.
South Carolina style mustard barbeque sauce is a good all-around sauce. It might take some getting used to, but it'll grow on you if you give it half a chance! 

== Source
https://www.smoker-cooking.com/mustardbarbequesauce.html[]