= Peach Barbeque
:keywords: 
:navtitle: 
:description:
:experimental: 
:hardbreaks-option:
:imagesdir: ../images
:source-highlighter: highlight.js
:icons: font
:table-stripes: even
:tabs:
:tabs-sync-option:

Ingredients
	• 1Tablespoonolive oil
	• ½cupyellow onion(minced)
	• 1large clovegarlic(pressed or finely minced)
	• ½teaspoonchipotle powder(or regular chili powder)
	• ½cupbourbon (I used Four Roses)
	• ½cupketchup
	• ¼cupmolasses
	• ¼cupbrown sugar(lightly packed)
	• 1TablespoonWorcestershire sauce
	• 1Tablespoonapple cider vinegar
	• 1 ½cupsripe peaches(chopped)
Instructions
	• Heat oil in a medium sauce pan over medium heat. Add the onion and cook until softened and golden brown.
	• Add the garlic and cook until fragrant, about one minute. Stir in the chili powder and cook for an additional minute or two.
	• Remove from heat and add the bourbon. (Do not stand directly above the pan or breathe in while adding the bourbon!!)
	• Stir in the ketchup, molasses, brown sugar, vinegar, and Worcestershire sauce.
	• Return to heat and stir until thoroughly combined. Pour in the peaches and stir to combine.
	• Bring to a boil, then reduce heat to LOW and simmer for 20 minutes until thickened. Remove from heat and puree with an immersion blender to break up the peaches and onions.
	• Allow sauce to cool before pouring into a glass jar or storage container. Store in the refrigerator for up to 3 weeks, assuming it lasts that long!
Notes
	• For a spicier sauce, add additional chili powder.
	• I use natural ketchup that does not contain high-fructose corn syrup.
	• For a perfectly smooth sauce, carefully pour into a blender and puree until smooth.
Check the sauce for sweetness and spiciness before you blend. Not all peaches are sweet, and everyone has a different spice tolerance.