= Chili
:keywords: 
:navtitle: 
:description:
:experimental: 
:hardbreaks-option:
:imagesdir: ../images
:source-highlighter: highlight.js
:icons: font
:table-stripes: even
:tabs:
:tabs-sync-option:

FOR THIS RECIPE YOU'LL NEED: 

BEANS: 
300 g dried pinto beans soaked overnight 
150g reserved bean liquid 

CHILE PASTE: 
20g dried ancho or about 3 chiles 
20g dried guajillo or about 3 chiles 
20g dried pasilla or about 3 chiles 
600g chicken stock or 2.5 cups (+ a little extra to deglaze the chili)

Bison: 
2lbs Ground Bison

CHILI BASE: 
1 red onion 
1 poblano 
4-5 cloves garlic, roughly chopped 
3-4 TBSP olive oil 
2g chili flake or 1/2ish tsp 
20g chili powder or 2.5 Tbsp 
20g paprika or 3Tbsp 
12g cumin or 1.5 Tbsp 
10g cocoa powder or 4tsp 
28oz can crushed toms 
28oz can diced toms, drained 
850g cooked beans or about 4.5 cups 150g bean liquid or about 2/3 cup 

SEASONING: 
30g brown sugar or 2.5 Tbsp 
20g hot sauce or 1.5 Tbsp 
20g worcestershire or 1.5 Tbsp 
40g cider vin or 1/8 cup 
15g salt or 2.5 tsp

FINAL SEASONING TO TASTE (if needed): 
brown sugar 
hot sauce 
cider vin 
salt 

1. pressure cook beans on high for 25 minutes with 1 kilo of water (or until tender but firm). reserve bean liquid. 
2. toast chiles in the oven at 450 degrees for 5-10min 
3. cut shortribs into 1-2 inch chunks then freeze on a sheet tray (about 15min) 
4. pull chilis from oven and remove seeds 
5. blend chilis with 600g beef stock to create chili paste and refrigerate until ready to use 
6. after freezing shortribs for 15min, using a food processor, process shortribs in 2 batches (pulse until beef looks like it does in the video) 
7. press ground meat onto a sheet on a sheet tray and broil in the oven on high for 3-5 minutes or until well browned (time will depend on your broiler) 
8. after well browned, break up and crumble the meat (i recommend by hand with gloves, but you do you) 

9. into a large heavy-bottomed pot, add onion and poblano to oil. sauté for 1-2 minutes 
10: once onion and poblano are starting to soften, add garlic followed by chili flake, chili powder, paprika, cumin, cocoa powder. stir to combine and let bloom for about 2 min 

11. deglaze with splash of beef stock 
12. add crushed and drained diced tomatoes, and chili paste you made earlier. stir 
13. add crumbled short rib, stir to combine 
14. put lid on pot and load into a 275 degree oven for 90 minutes 
15. after 90 minutes, add brown sugar, hot sauce, Worcestershire, cider vin, salt, cooked beans + 150g bean liquid and gently stir to incorporate 
16. load back into a 325 degree oven uncovered for 45 mins to caramelize and reduce 
17. after 45 minutes, taste and add your final seasonings to taste (salt, brown sugar, cider vinegar, hot sauce)

From <https://www.youtube.com/watch?v=8h7YSpu98Uc> 
